name: ecr push image

on:
  push:

env:
  # Dockerイメージのtarアーカイブ出力先のパス
  PATH_CACHE: /tmp/docker-img-arch
  # イメージを push する ECR リポジトリ名
  REPOSITORY: webspeedhackathon2023
  # 任意のイメージタグ
  IMAGE_TAG: 'latest'

jobs:
  push:
    runs-on: ubuntu-latest
    # `permissions` を設定しないと OIDC が使えないので注意
    permissions:
      id-token: write
      contents: read

    steps:
      # リポジトリの読み取り
      - uses: actions/checkout@v3

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::230806776430:role/webspeedhackathon2023-push-ecr-from-github-actions-role'

      # ECR ログイン
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr # outputs で参照するために id を設定

      # Dockerイメージをビルド
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true # イメージを保存する
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

      # Docker イメージを pushする
      - name: Push docker image to ecr
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
